(() => {
'use strict';
const D=window.CAMPUS_V5,$=id=>document.getElementById(id);
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const state={selected:null,start:null,destination:null,position:store.get('cn_position',null),cal:store.get('cn_calibration',{}),saved:new Set(store.get('cn_saved',[])),placing:null,tracking:false,heading:0,step:0,route:null,routeIndex:0,confidence:100};
const bounds=[[0,0],[D.image.height,D.image.width]];
const map=L.map('map',{crs:L.CRS.Simple,minZoom:-2,maxZoom:3,zoomControl:false,attributionControl:false});
L.imageOverlay(D.image.src,bounds,{interactive:false}).addTo(map);map.fitBounds(bounds,{padding:[10,10]});map.setMaxBounds([[-120,-120],[D.image.height+120,D.image.width+120]]);
const roomLayer=L.layerGroup().addTo(map),positionLayer=L.layerGroup().addTo(map),routeLayer=L.layerGroup().addTo(map);
function posFor(r){return state.cal[r.id]?.pos||r.pos||null}function verified(r){return !!state.cal[r.id]||!!r.verified}
function roomBy(q){q=(q||'').trim().toLowerCase();return D.rooms.find(r=>r.id.toLowerCase()===q)||D.rooms.find(r=>r.aliases.some(a=>a===q))||D.rooms.find(r=>r.aliases.some(a=>a.includes(q)))}
function toast(s){const t=$('toast');t.textContent=s;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,2600)}
function openSheet(id){$('backdrop').hidden=false;$(id).hidden=false}function closeSheets(){$('backdrop').hidden=true;document.querySelectorAll('.sheet').forEach(x=>x.hidden=true)}
function floorView(r){return D.floorViews[`${r.bldg}|${r.floor}`]}
function focusRoom(r){const p=posFor(r);if(p)map.flyTo(p,2,{duration:.5});else{const v=floorView(r);if(v)map.fitBounds(v.bounds,{padding:[45,45],animate:true})}}
function renderRooms(){roomLayer.clearLayers();for(const r of D.rooms){const p=posFor(r);if(!p)continue;const ok=verified(r);const icon=L.divIcon({className:'',html:`<div class="room-dot ${ok?'verified':'approx'}" title="${r.id}"></div>`,iconSize:[18,18],iconAnchor:[9,9]});L.marker(p,{icon}).addTo(roomLayer).on('click',()=>selectRoom(r));}updateAccuracy()}
function updateAccuracy(){const n=D.rooms.filter(verified).length;$('accuracyText').textContent=`${n}/${D.rooms.length} room pins verified`;const pct=Math.round(n/D.rooms.length*100);$('accuracyBadge').dataset.level=pct>70?'high':pct>30?'mid':'low';$('studioStats').textContent=`${n} verified positions · ${D.rooms.length-n} still need calibration.`}
function selectRoom(r){state.selected=r;focusRoom(r);$('roomName').textContent=r.id;const alias=r.aliases[0]?' · '+r.aliases[0].replace(/\b\w/g,c=>c.toUpperCase()):'';$('roomMeta').textContent=`${r.bldg} · ${floorLabel(r.floor)}${alias}`;$('roomAccuracy').textContent=verified(r)?'✓ Pin verified against floor plan':'Position not yet verified — the app will show the correct floor section instead of a fake pin.';$('roomAccuracy').className='room-accuracy '+(verified(r)?'good':'warn');$('saveRoom').textContent=state.saved.has(r.id)?'★ Saved':'☆ Save';openSheet('roomSheet')}
function floorLabel(f){return f==='G'?'Ground Floor':f==='LG'?'Lower Ground Floor':f==='1'?'First Floor':'Second Floor'}
function search(q=''){q=q.trim().toLowerCase();const rs=D.rooms.filter(r=>!q||r.id.toLowerCase().includes(q)||r.bldg.toLowerCase().includes(q)||r.aliases.some(a=>a.includes(q))).slice(0,80);$('searchResults').innerHTML=rs.map(r=>`<button class="result" data-room="${r.id}"><span><b>${r.id}</b><small>${r.bldg} · ${floorLabel(r.floor)}${r.aliases[0]?' · '+r.aliases[0]:''}</small></span><em>${verified(r)?'Verified':'Floor located'}</em></button>`).join('')||'<p class="empty">No matching room.</p>';document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{const r=roomBy(b.dataset.room);closeSheets();selectRoom(r)})}
function renderPosition(){positionLayer.clearLayers();if(!state.position)return;const p=state.position.pos;const icon=L.divIcon({className:'',html:`<div class="you"><i style="transform:rotate(${state.heading}deg)"></i><b></b></div>`,iconSize:[44,44],iconAnchor:[22,22]});L.marker(p,{icon,zIndexOffset:2000}).addTo(positionLayer);$('positionInfo').textContent=`Position source: ${state.position.source||'manual'} · confidence ${Math.round(state.confidence)}%`}
function setPosition(pos,source='map',roomId=null){state.position={pos,source,roomId,at:Date.now()};state.confidence=source==='room'?100:90;store.set('cn_position',state.position);renderPosition();map.flyTo(pos,2);toast('Position set')}
function calibrationMode(room){state.placing=room;closeSheets();toast(`Tap the exact position for ${room.id}`);$('map').classList.add('calibrating')}
map.on('click',e=>{if(state.placing){state.cal[state.placing.id]={pos:[+e.latlng.lat.toFixed(1),+e.latlng.lng.toFixed(1)],verifiedAt:new Date().toISOString()};store.set('cn_calibration',state.cal);const id=state.placing.id;state.placing=null;$('map').classList.remove('calibrating');renderRooms();toast(`${id} position saved and verified`);return}if(state.tapPosition){state.tapPosition=false;setPosition([e.latlng.lat,e.latlng.lng],'map');$('map').classList.remove('calibrating')}});
function routeTo(dest){if(!state.start&&state.position?.roomId)state.start=roomBy(state.position.roomId);if(!state.start){state.destination=dest;toast('Set where you are first');openPosition();return}state.destination=dest;buildRoute(state.start,dest)}
function buildRoute(a,b){const key=`${a.id}>${b.id}`,special=D.specialRoutes[key];let steps;if(special)steps=special;else if(a.bldg===b.bldg&&a.floor===b.floor){steps=[`Start at ${a.id}.`,`Follow the signed corridor on ${a.bldg} ${floorLabel(a.floor)} toward ${b.id}.`,`Arrive at ${b.id}.`]}else{steps=[`Start at ${a.id} in ${a.bldg} (${floorLabel(a.floor)}).`,`Follow campus signs to ${b.bldg}.`,a.floor!==b.floor?`Use the appropriate stairs or lift to reach ${floorLabel(b.floor)}.`:`Stay on ${floorLabel(b.floor)}.`,`Continue to ${b.id}.`]}state.route={a,b,steps};state.routeIndex=0;closeSheets();renderRoute();drawRoute();$('routeCard').hidden=false}
function drawRoute(){routeLayer.clearLayers();if(!state.route)return;const pa=posFor(state.route.a),pb=posFor(state.route.b);if(pa&&pb&&state.route.a.bldg===state.route.b.bldg&&state.route.a.floor===state.route.b.floor)L.polyline([pa,pb],{weight:7,opacity:.85,dashArray:'12 10'}).addTo(routeLayer);if(pb)map.fitBounds([pa||pb,pb],{padding:[80,80]});else focusRoom(state.route.b)}
function renderRoute(){const r=state.route;if(!r)return;$('routeTitle').textContent=`${r.a.id} → ${r.b.id}`;$('routeStatus').textContent=`Step ${state.routeIndex+1} of ${r.steps.length}`;$('nextInstruction').textContent=r.steps[state.routeIndex];$('routeSteps').innerHTML=r.steps.map((s,i)=>`<li class="${i===state.routeIndex?'current':''}">${s}</li>`).join('')}
function speak(){if(!state.route||!('speechSynthesis'in window))return;speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(state.route.steps[state.routeIndex]))}
function openPosition(){$('positionInfo').textContent=state.position?`Current source: ${state.position.source}`:'No indoor position set.';openSheet('positionSheet')}
async function enableTracking(){if(!state.position){openPosition();return}try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')throw new Error('orientation denied')}if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){const p=await DeviceMotionEvent.requestPermission();if(p!=='granted')throw new Error('motion denied')}state.tracking=!state.tracking;$('trackingBtn').classList.toggle('active',state.tracking);$('trackingBtn').textContent=state.tracking?'◉ Following':'◉ Follow me';toast(state.tracking?'Assisted tracking started':'Tracking stopped')}catch(e){toast('Motion permission was not granted')}}
let lastMag=0,lastStepAt=0;window.addEventListener('deviceorientation',e=>{let h=e.webkitCompassHeading??(e.alpha!=null?360-e.alpha:null);if(h==null)return;state.heading=h;renderPosition()});window.addEventListener('devicemotion',e=>{if(!state.tracking||!state.position)return;const a=e.accelerationIncludingGravity;if(!a)return;const mag=Math.sqrt((a.x||0)**2+(a.y||0)**2+(a.z||0)**2);const now=Date.now();if(lastMag&&Math.abs(mag-lastMag)>2.2&&now-lastStepAt>420){lastStepAt=now;state.step++;const rad=state.heading*Math.PI/180,px=10;state.position.pos=[state.position.pos[0]-Math.cos(rad)*px,state.position.pos[1]+Math.sin(rad)*px];state.position.source='assisted tracking';state.confidence=Math.max(35,state.confidence-.7);store.set('cn_position',state.position);renderPosition();if(state.route&&posFor(state.route.b)){const p=posFor(state.route.b),d=Math.hypot(p[0]-state.position.pos[0],p[1]-state.position.pos[1]);if(d<45&&state.routeIndex<state.route.steps.length-1){state.routeIndex++;renderRoute();speak()}}}lastMag=mag});
function assistant(msg){const text=msg.trim();if(!text)return;addFeed(text,'me');const low=text.toLowerCase();let m=low.match(/(?:i(?:'m| am) at|start(?:ing)? at|from)\s+([a-z]\d{3}[a-z]?)/i);if(m){const r=roomBy(m[1]);if(r){state.start=r;const p=posFor(r);if(p)setPosition(p,'room',r.id);addFeed(`Got it — I’ll use ${r.id} as your starting point.`,'bot');return}}m=low.match(/(?:take me to|go to|directions to|find|where is|step[- ]?free to)\s+([a-z]\d{3}[a-z]?|.+)$/i);if(m){let q=m[1].replace(/[?.!]+$/,'').trim(),r=roomBy(q);if(!r){r=D.rooms.find(x=>x.aliases.some(a=>q.includes(a)))}if(r){addFeed(`${r.id} is in ${r.bldg}, ${floorLabel(r.floor)}. ${verified(r)?'Its map pin is verified.':'Its floor is known, but the exact room pin still needs calibration.'}`,'bot');focusRoom(r);if(low.startsWith('take')||low.includes('directions')||low.includes('step-free'))routeTo(r);return}}addFeed('I can set your starting room, find rooms, and start guidance. Try “I’m at B007” then “take me to B014”.','bot')}
function addFeed(s,who){const d=document.createElement('div');d.className=who;d.textContent=s;$('assistantFeed').appendChild(d);$('assistantFeed').scrollTop=$('assistantFeed').scrollHeight}
function showAssistant(){$('assistantCard').hidden=false;$('assistantInput').focus()}
$('searchBtn').onclick=()=>{search();openSheet('searchSheet');setTimeout(()=>$('roomSearch').focus(),50)};$('roomSearch').oninput=e=>search(e.target.value);$('backdrop').onclick=closeSheets;document.querySelectorAll('.close').forEach(b=>b.onclick=closeSheets);
$('assistantBtn').onclick=showAssistant;$('assistantClose').onclick=()=>$('assistantCard').hidden=true;$('assistantSend').onclick=()=>{const v=$('assistantInput').value;$('assistantInput').value='';assistant(v)};$('assistantInput').onkeydown=e=>{if(e.key==='Enter')$('assistantSend').click()};
$('locateBtn').onclick=openPosition;$('trackingBtn').onclick=enableTracking;$('tapStart').onclick=()=>{closeSheets();state.tapPosition=true;$('map').classList.add('calibrating');toast('Tap your exact location')};$('chooseStart').onclick=()=>{closeSheets();search();openSheet('searchSheet');toast('Choose your current room, then tap “I’m here”')};
$('setHere').onclick=()=>{const r=state.selected,p=posFor(r);state.start=r;if(p)setPosition(p,'room',r.id);else toast('Room pin must be calibrated before it can set an exact position');closeSheets()};$('goHere').onclick=()=>routeTo(state.selected);$('saveRoom').onclick=()=>{const id=state.selected.id;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);store.set('cn_saved',[...state.saved]);selectRoom(state.selected)};$('calibrateRoom').onclick=()=>calibrationMode(state.selected);
$('studioBtn').onclick=()=>{renderStudio();openSheet('studioSheet')};function renderStudio(){const sorted=[...D.rooms].sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true}));$('studioRoom').innerHTML=sorted.map(r=>`<option value="${r.id}">${r.id} — ${r.bldg} ${r.floor}${verified(r)?' ✓':''}</option>`).join('');updateAccuracy()}$('studioPlace').onclick=()=>calibrationMode(roomBy($('studioRoom').value));$('exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,created:new Date().toISOString(),calibration:state.cal},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='campus-map-calibration.json';a.click();URL.revokeObjectURL(a.href)};$('importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const j=JSON.parse(rd.result);state.cal=j.calibration||j;store.set('cn_calibration',state.cal);renderRooms();renderStudio();toast('Calibration imported')}catch{toast('Invalid calibration file')}};rd.readAsText(f)};$('clearCalibration').onclick=()=>{if(confirm('Clear all local room corrections?')){state.cal={};store.set('cn_calibration',{});renderRooms();renderStudio()}};
$('nextStep').onclick=()=>{if(state.route&&state.routeIndex<state.route.steps.length-1){state.routeIndex++;renderRoute()}};$('prevStep').onclick=()=>{if(state.route&&state.routeIndex>0){state.routeIndex--;renderRoute()}};$('speakStep').onclick=speak;$('endRoute').onclick=()=>{state.route=null;routeLayer.clearLayers();$('routeCard').hidden=true};
$('menuBtn').onclick=()=>toast('Campus Navigator v5 · verified-room wayfinding');document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=b.dataset.tab;if(t==='search')$('searchBtn').click();if(t==='assistant')showAssistant();if(t==='saved'){search('');openSheet('searchSheet');$('searchResults').innerHTML=[...state.saved].map(id=>`<button class="result" data-room="${id}"><b>${id}</b></button>`).join('')||'<p class="empty">No saved rooms yet.</p>';document.querySelectorAll('[data-room]').forEach(x=>x.onclick=()=>{closeSheets();selectRoom(roomBy(x.dataset.room))})}});
window.addEventListener('online',()=>$('offline').hidden=true);window.addEventListener('offline',()=>$('offline').hidden=false);$('offline').hidden=navigator.onLine;
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
renderRooms();renderPosition();search();renderStudio();
})();
