(() => {
'use strict';
const D=window.CAMPUS_V6||window.CAMPUS_V5,$=id=>document.getElementById(id);
if(!D){document.body.innerHTML='<div style="padding:24px;font-family:system-ui">Campus data failed to load.</div>';return;}
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
const EMPTY_SURVEY={checkpoints:[],edges:[]};
const state={
 selected:null,start:null,destination:null,position:store.get('cn_position',null),cal:store.get('cn_calibration',{}),
 survey:store.get('cn_survey',EMPTY_SURVEY),saved:new Set(store.get('cn_saved',[])),placing:null,placingAnchor:null,tapPosition:false,
 tracking:false,heading:0,route:null,routeIndex:0,confidence:store.get('cn_confidence',100),scale:1,tx:0,ty:0,
 stepFree:store.get('cn_stepfree',false),voice:store.get('cn_voice',false),tourLoaded:false,
 profile:store.get('cn_profile','student'),lastConfirmed:store.get('cn_lastConfirmed',null)
};
if(!state.survey||!Array.isArray(state.survey.checkpoints)||!Array.isArray(state.survey.edges))state.survey=structuredClone(EMPTY_SURVEY);
for(const key of [...state.saved]){if(!String(key).includes(':')){state.saved.delete(key);state.saved.add('room:'+key)}}store.set('cn_saved',[...state.saved]);

/* ---------- zero-dependency image map engine ---------- */
const mapEl=$('map');
mapEl.innerHTML=`<div id="mapStage" class="map-stage"><img id="floorImage" draggable="false" alt="Campus floor plans"><svg id="routeSvg" class="route-svg" viewBox="0 0 ${D.image.width} ${D.image.height}" preserveAspectRatio="none"></svg><div id="roomLayer" class="map-layer"></div><div id="checkpointLayer" class="map-layer"></div><div id="positionLayer" class="map-layer"></div></div>`;
const stage=$('mapStage'),img=$('floorImage'),roomLayer=$('roomLayer'),checkpointLayer=$('checkpointLayer'),positionLayer=$('positionLayer'),routeSvg=$('routeSvg');
img.src=D.image.src;stage.style.width=D.image.width+'px';stage.style.height=D.image.height+'px';
function applyTransform(){stage.style.transform=`translate3d(${state.tx}px,${state.ty}px,0) scale(${state.scale})`;}
function fitBounds(bounds,animate=true){const [[y1,x1],[y2,x2]]=bounds,w=Math.max(10,x2-x1),h=Math.max(10,y2-y1),cw=mapEl.clientWidth||innerWidth,ch=mapEl.clientHeight||innerHeight;let s=Math.min(cw/w,ch/h)*.86;s=Math.max(.2,Math.min(4,s));const cx=(x1+x2)/2,cy=(y1+y2)/2;state.scale=s;state.tx=cw/2-cx*s;state.ty=ch/2-cy*s;stage.classList.toggle('animate-map',animate);applyTransform();setTimeout(()=>stage.classList.remove('animate-map'),350)}
function fitAll(){fitBounds([[0,0],[D.image.height,D.image.width]])}
function flyTo(pos,scale=2.15){const [y,x]=pos,cw=mapEl.clientWidth,ch=mapEl.clientHeight;state.scale=Math.max(.3,Math.min(4,scale));state.tx=cw/2-x*state.scale;state.ty=ch/2-y*state.scale;stage.classList.add('animate-map');applyTransform();setTimeout(()=>stage.classList.remove('animate-map'),350)}
function screenToMap(clientX,clientY){const r=mapEl.getBoundingClientRect();return [(clientY-r.top-state.ty)/state.scale,(clientX-r.left-state.tx)/state.scale]}
let pointers=new Map(),dragStart=null,lastTap=0;
mapEl.addEventListener('pointerdown',e=>{if(e.target.closest('button,.room-hit,.checkpoint-hit'))return;mapEl.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)dragStart={x:e.clientX,y:e.clientY,tx:state.tx,ty:state.ty,moved:false};});
mapEl.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&dragStart){const dx=e.clientX-dragStart.x,dy=e.clientY-dragStart.y;if(Math.abs(dx)+Math.abs(dy)>4)dragStart.moved=true;state.tx=dragStart.tx+dx;state.ty=dragStart.ty+dy;applyTransform();}else if(pointers.size===2){const pts=[...pointers.values()];const before=[...pointers.entries()].map(([id,p])=>id===e.pointerId?old:p);const d0=Math.hypot(before[0].x-before[1].x,before[0].y-before[1].y),d1=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);if(d0>0&&d1>0){const mx=(pts[0].x+pts[1].x)/2,my=(pts[0].y+pts[1].y)/2;const mapPt=screenToMap(mx,my);const ns=Math.max(.2,Math.min(4,state.scale*(d1/d0)));const r=mapEl.getBoundingClientRect();state.scale=ns;state.tx=mx-r.left-mapPt[1]*ns;state.ty=my-r.top-mapPt[0]*ns;applyTransform();}}});
function pointerEnd(e){const was=dragStart,p=pointers.get(e.pointerId);pointers.delete(e.pointerId);if(pointers.size===0){if(was&&!was.moved&&p){const now=Date.now();if(now-lastTap<300){const [y,x]=screenToMap(e.clientX,e.clientY);flyTo([y,x],Math.min(4,state.scale*1.55));}else handleMapTap(e.clientX,e.clientY);lastTap=now;}dragStart=null;}else if(pointers.size===1){const p=[...pointers.values()][0];dragStart={x:p.x,y:p.y,tx:state.tx,ty:state.ty,moved:true};}}
mapEl.addEventListener('pointerup',pointerEnd);mapEl.addEventListener('pointercancel',pointerEnd);
mapEl.addEventListener('wheel',e=>{e.preventDefault();const [y,x]=screenToMap(e.clientX,e.clientY);const ns=Math.max(.2,Math.min(4,state.scale*(e.deltaY<0?1.15:.87)));const r=mapEl.getBoundingClientRect();state.scale=ns;state.tx=e.clientX-r.left-x*ns;state.ty=e.clientY-r.top-y*ns;applyTransform();},{passive:false});
function handleMapTap(cx,cy){const [y,x]=screenToMap(cx,cy);if(state.placing){state.cal[state.placing.id]={pos:[+y.toFixed(1),+x.toFixed(1)],verifiedAt:new Date().toISOString()};store.set('cn_calibration',state.cal);const id=state.placing.id;state.placing=null;mapEl.classList.remove('calibrating');renderRooms();renderStudio();toast(`${id} doorway verified`);return}if(state.placingAnchor){const a={...state.placingAnchor,pos:[+y.toFixed(1),+x.toFixed(1)],verified:true,createdAt:new Date().toISOString()};state.survey.checkpoints.push(a);state.placingAnchor=null;mapEl.classList.remove('calibrating');saveSurvey();renderCheckpoints();renderStudio();toast(`${a.name} anchor saved`);return}if(state.tapPosition){state.tapPosition=false;mapEl.classList.remove('calibrating');setPosition([y,x],'manual map pin',null,null,88)}}
img.addEventListener('load',()=>{fitAll();setTimeout(updateAccuracy,0)});window.addEventListener('resize',()=>{if(!state.selected&&!state.route)fitAll()});

/* ---------- campus entities ---------- */
function posFor(r){return state.cal[r.id]?.pos||r.pos||null}
function verified(r){return !!state.cal[r.id]||!!r.verified}
function roomBy(q){q=(q||'').trim().toLowerCase();return D.rooms.find(r=>r.id.toLowerCase()===q)||D.rooms.find(r=>(r.aliases||[]).some(a=>a.toLowerCase()===q))||null}
function placeBy(id){return D.places.find(p=>p.id===id)||null}
function floorLabel(f){return f==='G'?'Ground Floor':f==='LG'?'Lower Ground Floor':f==='1'?'First Floor':f==='2'?'Second Floor':f}
function floorView(r){return D.floorViews[`${r.bldg}|${r.floor}`]}
function entityKey(sel){return !sel?null:sel.type==='room'?`room:${sel.value.id}`:`place:${sel.value.id}`}
function targetRoom(sel){if(!sel)return null;if(sel.type==='room')return sel.value;if(sel.type==='place'&&sel.value.room)return roomBy(sel.value.room);return null}
function labelFor(sel){return !sel?'':sel.type==='room'?sel.value.id:sel.value.name}
function toast(s){const t=$('toast');t.textContent=s;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,3000)}
function focusRoom(r){const p=posFor(r);if(p)flyTo(p,2.25);else{const v=floorView(r);if(v)fitBounds(v.bounds)}}
function saveSurvey(){store.set('cn_survey',state.survey)}
function allCheckpoints(){const merged=new Map();for(const c of D.checkpoints||[])merged.set(c.id,{...c,seed:true});for(const c of state.survey.checkpoints||[])merged.set(c.id,{...c,seed:false});return [...merged.values()]}
function checkpointBy(id){return allCheckpoints().find(c=>c.id===id)||null}
function checkpointMatches(text){const q=norm(text);return allCheckpoints().map(c=>({c,score:[c.name,c.type,c.id,...(c.keywords||[])].map(norm).reduce((n,h)=>n+(h&&q.includes(h)?40:h&&h.includes(q)?25:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)}
function renderRooms(){roomLayer.innerHTML='';for(const r of D.rooms){const p=posFor(r);if(!p)continue;const b=document.createElement('button');b.className='room-hit verified';b.style.left=p[1]+'px';b.style.top=p[0]+'px';b.title=r.id;b.setAttribute('aria-label',`Room ${r.id}`);b.innerHTML='<span></span>';b.onclick=e=>{e.stopPropagation();selectEntity({type:'room',value:r})};roomLayer.appendChild(b)}updateAccuracy()}
function renderCheckpoints(){checkpointLayer.innerHTML='';for(const c of allCheckpoints()){if(!c.pos||c.type==='room')continue;const b=document.createElement('button');b.className=`checkpoint-hit ${c.verified?'verified':''}`;b.style.left=c.pos[1]+'px';b.style.top=c.pos[0]+'px';b.title=c.name;b.setAttribute('aria-label',c.name);b.innerHTML=`<span>${checkpointIcon(c.type)}</span>`;b.onclick=e=>{e.stopPropagation();anchorAt(c)};checkpointLayer.appendChild(b)}}
function checkpointIcon(type){return ({entrance:'↗',junction:'⌁',stairs:'⇅',lift:'↕',toilet:'WC',printer:'▣',water:'◌',landmark:'◉',room:'•'})[type]||'◉'}
function updateAccuracy(){const rooms=D.rooms.filter(verified).length,anchors=allCheckpoints().filter(c=>c.pos&&c.verified).length,links=(state.survey.edges||[]).length;const roomPct=Math.round(rooms/D.rooms.length*100);$('accuracyText').textContent=`${rooms} rooms · ${anchors} anchors`; $('accuracyBadge').dataset.level=roomPct>=70?'high':roomPct>=30?'mid':'low';if($('studioStats'))$('studioStats').innerHTML=`<b>${rooms}/${D.rooms.length}</b> precise room-door pins · <b>${anchors}</b> precise anchors · <b>${links}</b> surveyed links.<br>Unverified rooms remain floor-located rather than being given fake coordinates.`}

/* ---------- sheets ---------- */
function openSheet(id){closeSheets(false);$('backdrop').hidden=false;$(id).hidden=false}
function closeSheets(hideBackdrop=true){document.querySelectorAll('.sheet').forEach(x=>x.hidden=true);if(hideBackdrop)$('backdrop').hidden=true}
$('backdrop').onclick=()=>closeSheets();document.querySelectorAll('.close').forEach(b=>b.onclick=()=>closeSheets());

/* ---------- destination detail ---------- */
function selectEntity(sel){state.selected=sel;const r=targetRoom(sel);if(r)focusRoom(r);const isRoom=sel.type==='room',v=sel.value;
 $('roomKind').textContent=isRoom?'ROOM':'DESTINATION';$('roomName').textContent=isRoom?v.id:v.name;
 if(isRoom){$('roomMeta').textContent=`${v.bldg} · ${floorLabel(v.floor)}${(v.aliases||[])[0]?' · '+v.aliases[0]:''}`;$('destinationDescription').textContent='';$('roomAccuracy').textContent=verified(v)?'✓ Precise room-door pin verified':'Correct building and floor are known; the exact doorway is not yet survey-verified.';$('roomAccuracy').className='room-accuracy '+(verified(v)?'good':'warn');$('calibrateRoom').hidden=false;}
 else {const linked=r?`Linked to ${r.id} · ${r.bldg} · ${floorLabel(r.floor)}`:'Current campus destination; exact map anchor still being surveyed.';$('roomMeta').textContent=`${v.kind} · ${linked}`;$('destinationDescription').textContent=v.description||'';$('roomAccuracy').textContent=r&&verified(r)?'✓ Destination linked to a verified room pin':'Use Explore for a real visual look while exact indoor anchors are being surveyed.';$('roomAccuracy').className='room-accuracy '+(r&&verified(r)?'good':'warn');$('calibrateRoom').hidden=true;}
 const key=entityKey(sel);$('saveRoom').textContent=state.saved.has(key)?'★ Saved':'☆ Save';$('goHere').textContent=r?'Start guidance':'Explore in 360°';openSheet('roomSheet')}
$('setHere').onclick=()=>{const r=targetRoom(state.selected);if(!r){toast('Choose a precise room as your starting point');return}const p=posFor(r);state.start=r;if(p){const cp=allCheckpoints().find(c=>c.room===r.id&&c.pos);setPosition(p,'verified room',r.id,cp?.id||null,100);closeSheets()}else toast('This room needs an exact pin before it can be a precise start')};
$('goHere').onclick=()=>{const r=targetRoom(state.selected);if(r)routeTo(r);else openTour()};$('lookAround').onclick=openTour;
$('saveRoom').onclick=()=>{const key=entityKey(state.selected);if(!key)return;state.saved.has(key)?state.saved.delete(key):state.saved.add(key);store.set('cn_saved',[...state.saved]);selectEntity(state.selected)};
$('calibrateRoom').onclick=()=>{if(state.selected?.type==='room')calibrationMode(state.selected.value)};

/* ---------- search ---------- */
function norm(s){return (s||'').toLowerCase().replace(/[^a-z0-9 ]+/g,' ').replace(/\s+/g,' ').trim()}
function scoreEntity(q,sel){const n=norm(q);if(!n)return 1;if(sel.type==='room'){const r=sel.value,hay=norm([r.id,r.bldg,...(r.aliases||[])].join(' '));if(norm(r.id)===n)return 100;if(hay.includes(n))return 60;return n.split(' ').reduce((s,w)=>s+(hay.includes(w)?6:0),0)}const p=sel.value,hay=norm([p.name,p.kind,p.description,...(p.keywords||[])].join(' '));if(norm(p.name)===n)return 95;if((p.keywords||[]).some(k=>norm(k)===n))return 85;if(hay.includes(n))return 55;return n.split(' ').reduce((s,w)=>s+(hay.includes(w)?7:0),0)}
function allEntities(){return [...D.places.map(value=>({type:'place',value})),...D.rooms.map(value=>({type:'room',value}))]}
function resultMarkup(sel){if(sel.type==='place'){const p=sel.value,r=targetRoom(sel);return `<button class="result" data-kind="place" data-id="${p.id}"><span class="result-icon">${p.icon||'•'}</span><span class="result-copy"><b>${p.name}</b><small>${p.kind}${r?' · '+r.id:''}</small></span><em>${r&&verified(r)?'Verified':'Explore'}</em></button>`}const r=sel.value;return `<button class="result" data-kind="room" data-id="${r.id}"><span class="result-icon">${r.id[0]}</span><span class="result-copy"><b>${r.id}</b><small>${r.bldg} · ${floorLabel(r.floor)}${(r.aliases||[])[0]?' · '+r.aliases[0]:''}</small></span><em>${verified(r)?'Precise':'Floor only'}</em></button>`}
function bindResults(root=$('searchResults')){root.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{const sel=b.dataset.kind==='room'?{type:'room',value:roomBy(b.dataset.id)}:{type:'place',value:placeBy(b.dataset.id)};closeSheets();selectEntity(sel)})}
function search(q=''){const scored=allEntities().map(sel=>({sel,score:scoreEntity(q,sel)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||(a.sel.type==='place'?-1:1)).slice(0,q?60:24);$('searchResults').innerHTML=scored.map(x=>resultMarkup(x.sel)).join('')||'<p class="empty">No matching destination. Try describing what you need.</p>';bindResults()}
$('searchBtn').onclick=()=>{search();openSheet('searchSheet');setTimeout(()=>$('roomSearch').focus(),50)};$('roomSearch').oninput=e=>search(e.target.value);

/* ---------- position & assisted tracking ---------- */
function renderPosition(){positionLayer.innerHTML='';if(!state.position)return;const p=state.position.pos;if(p){const d=document.createElement('div');d.className='you';d.style.left=p[1]+'px';d.style.top=p[0]+'px';d.innerHTML=`<i style="transform:translate(-50%,-100%) rotate(${state.heading}deg)"></i><b></b>`;positionLayer.appendChild(d)}if($('positionInfo')){const last=state.lastConfirmed?` Last confirmed: ${state.lastConfirmed.name}.`:'';$('positionInfo').textContent=`Position source: ${state.position.source||'manual'} · confidence ${Math.round(state.confidence)}%.${last} Follow Me is an estimate between anchors.`}}
function setPosition(pos,source='manual map pin',roomId=null,checkpointId=null,confidence=88){state.position={pos,source,roomId,checkpointId,at:Date.now()};state.confidence=confidence;store.set('cn_position',state.position);store.set('cn_confidence',state.confidence);renderPosition();if(pos)flyTo(pos,2.2);toast('Indoor position set')}
function openPosition(){$('positionInfo').textContent=state.position?`Current source: ${state.position.source}. Confidence ${Math.round(state.confidence)}%.`:'No indoor position set.';openSheet('positionSheet')}
$('tapStart').onclick=()=>{closeSheets();state.tapPosition=true;mapEl.classList.add('calibrating');toast('Tap your exact current position')};$('chooseStart').onclick=()=>{closeSheets();search();openSheet('searchSheet');toast('Choose your current room, then tap “I’m here”')};$('followMeBtn').onclick=enableTracking;$('landmarkStart').onclick=openLandmarks;
async function enableTracking(){if(!state.position){openPosition();return}try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')throw new Error()}if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){const p=await DeviceMotionEvent.requestPermission();if(p!=='granted')throw new Error()}state.tracking=!state.tracking;toast(state.tracking?'Follow Me started — confirm landmarks to remove drift':'Follow Me stopped')}catch{toast('Motion permission was not granted')}}
let lastMag=0,lastStepAt=0;window.addEventListener('deviceorientation',e=>{const h=e.webkitCompassHeading??(e.alpha!=null?360-e.alpha:null);if(h==null)return;state.heading=h;renderPosition();renderGuideLens()});window.addEventListener('devicemotion',e=>{if(!state.tracking||!state.position?.pos)return;const a=e.accelerationIncludingGravity;if(!a)return;const mag=Math.sqrt((a.x||0)**2+(a.y||0)**2+(a.z||0)**2),now=Date.now();if(lastMag&&Math.abs(mag-lastMag)>2.2&&now-lastStepAt>420){lastStepAt=now;const rad=state.heading*Math.PI/180,px=10;state.position.pos=[state.position.pos[0]-Math.cos(rad)*px,state.position.pos[1]+Math.sin(rad)*px];state.position.source='assisted dead-reckoning';state.confidence=Math.max(25,state.confidence-.8);store.set('cn_position',state.position);store.set('cn_confidence',state.confidence);renderPosition()}lastMag=mag});
function anchorAt(c){if(c.pos){setPosition(c.pos,`confirmed landmark: ${c.name}`,c.room||null,c.id,100)}else{state.position={pos:state.position?.pos||null,source:`semantic landmark: ${c.name}`,roomId:c.room||null,checkpointId:c.id,at:Date.now()};state.confidence=Math.max(state.confidence,80);store.set('cn_position',state.position);renderPosition()}state.lastConfirmed={id:c.id,name:c.name,at:Date.now()};store.set('cn_lastConfirmed',state.lastConfirmed);const idx=state.route?.steps?.findIndex(s=>s.anchor===c.id);if(idx>=0&&idx>=state.routeIndex){state.routeIndex=idx;renderRoute()}toast(`Confirmed: ${c.name}`)}
function openLandmarks(){const cps=allCheckpoints();let list=cps;if(state.start)list=cps.filter(c=>!c.bldg||c.bldg===state.start.bldg);if(state.route){const ids=new Set(state.route.steps.map(s=>s.anchor).filter(Boolean));list=[...cps.filter(c=>ids.has(c.id)),...cps.filter(c=>!ids.has(c.id))]}$('landmarkResults').innerHTML=list.slice(0,30).map(c=>`<button class="result" data-cp="${c.id}"><span class="result-icon">${checkpointIcon(c.type)}</span><span class="result-copy"><b>${c.name}</b><small>${c.bldg||'Campus'}${c.floor?' · '+floorLabel(c.floor):''}${c.pos?' · map anchor':''}</small></span><em>${c.verified?'Precise':'Route'}</em></button>`).join('')||'<p class="empty">No landmarks surveyed yet.</p>';$('landmarkResults').querySelectorAll('[data-cp]').forEach(b=>b.onclick=()=>{const c=checkpointBy(b.dataset.cp);if(c){anchorAt(c);closeSheets()}});openSheet('landmarkSheet')}
$('landmarkTour').onclick=openTour;

/* ---------- guidance ---------- */
function calibrationMode(room){state.placing=room;closeSheets();toast(`Tap the exact doorway for ${room.id}`);mapEl.classList.add('calibrating')}
function routeTo(dest){if(!state.start&&state.position?.roomId)state.start=roomBy(state.position.roomId);if(!state.start){state.destination=dest;toast('Tell me where you are first');openPosition();return}state.destination=dest;buildRoute(state.start,dest)}
function accessAllowed(edge){return edge.access!=='staff'||state.profile==='staff'}
function surveyedPath(a,b){const cps=allCheckpoints(),edges=state.survey.edges||[];const starts=cps.filter(c=>c.room===a.id&&c.pos),ends=cps.filter(c=>c.room===b.id&&c.pos);if(!starts.length||!ends.length||!edges.length)return null;const byId=new Map(cps.map(c=>[c.id,c])),adj=new Map();for(const e of edges){if(!accessAllowed(e))continue;if(state.stepFree&&e.stepFree===false)continue;if(!adj.has(e.from))adj.set(e.from,[]);if(!adj.has(e.to))adj.set(e.to,[]);adj.get(e.from).push({to:e.to,e});if(e.oneWay!==true)adj.get(e.to).push({to:e.from,e:{...e,instruction:e.reverseInstruction||e.instruction}})}const targetIds=new Set(ends.map(x=>x.id)),dist=new Map(),prev=new Map(),q=[];for(const s of starts){dist.set(s.id,0);q.push(s.id)}while(q.length){q.sort((x,y)=>(dist.get(x)??Infinity)-(dist.get(y)??Infinity));const u=q.shift();if(targetIds.has(u)){const chain=[];let cur=u;while(prev.has(cur)){const p=prev.get(cur);chain.unshift({from:p.from,to:cur,edge:p.edge});cur=p.from}return chain}for(const n of adj.get(u)||[]){const cu=byId.get(u),cv=byId.get(n.to),w=n.e.weight||((cu?.pos&&cv?.pos)?Math.hypot(cu.pos[0]-cv.pos[0],cu.pos[1]-cv.pos[1]):100);const nd=(dist.get(u)||0)+w;if(nd<(dist.get(n.to)??Infinity)){dist.set(n.to,nd);prev.set(n.to,{from:u,edge:n.e});if(!q.includes(n.to))q.push(n.to)}}}return null}
function buildRoute(a,b){const key=`${a.id}>${b.id}`,template=D.routeTemplates?.[key];let steps,precision='orientation only',note='';const graphPath=surveyedPath(a,b);if(graphPath&&graphPath.length){steps=graphPath.map((seg,i)=>{const to=checkpointBy(seg.to);return {action:i===graphPath.length-1?'arrive':'continue',icon:i===graphPath.length-1?'✓':'↑',text:seg.edge.instruction||`Continue to ${to?.name||seg.to}.`,anchor:seg.to,confirm:to?`Look for ${to.name}.`:''}});precision='survey graph';note='Built from surveyed anchor-to-anchor links.'}else if(template){steps=template.steps.map(x=>({...x}));precision=template.precision==='landmark-verified'?'verified landmark route':template.precision;note=template.note||''}else if(a.bldg===b.bldg&&a.floor===b.floor){steps=[{action:'start',icon:'●',text:`Start at ${a.id}.`,anchor:null,confirm:''},{action:'follow',icon:'↑',text:`Follow ${a.bldg} ${floorLabel(a.floor)} room signage toward ${b.id}.`,anchor:null,confirm:'Use visible room numbers to stay oriented.'},{action:'visual',icon:'◉',text:'Use the 360° visual check if the corridor does not match what you expect.',anchor:null,confirm:'Compare what you see with the real building tour.'},{action:'arrive',icon:'✓',text:`Arrive at ${b.id}.`,anchor:null,confirm:''}];precision='floor-level guidance'}else{steps=[{action:'start',icon:'●',text:`Start at ${a.id} in ${a.bldg}, ${floorLabel(a.floor)}.`,anchor:null,confirm:''},{action:'circulation',icon:'↑',text:`Follow signed campus circulation toward ${b.bldg}.`,anchor:null,confirm:'Use building names and corridor signage.'},{action:'level',icon:state.stepFree?'↕':'⇅',text:a.floor!==b.floor?(state.stepFree?`Use a signed accessible lift/step-free connection to ${floorLabel(b.floor)}. If a step-free connection is not clearly signed, use Visual check or ask staff.`:`Move to ${floorLabel(b.floor)} using signed stairs or a lift.`):`Remain on ${floorLabel(b.floor)}.`,anchor:null,confirm:''},{action:'arrive',icon:'✓',text:`Continue to ${b.id}.`,anchor:null,confirm:''}];precision='building/floor guidance'}
 state.route={a,b,steps,precision,note};state.routeIndex=0;closeSheets();$('guideLens').hidden=false;renderRoute();focusRoute();$('routeCard').hidden=false;$('welcomeCard').hidden=true;if(state.voice)setTimeout(speak,150)}
function focusRoute(){routeSvg.innerHTML='';if(!state.route)return;const a=state.route.a,b=state.route.b,pa=posFor(a),pb=posFor(b);const anchored=state.route.steps.filter(s=>s.anchor),points=anchored.map(s=>checkpointBy(s.anchor)?.pos).filter(Boolean),completeGeometry=anchored.length>1&&points.length===anchored.length;if(state.route.precision==='survey graph'&&completeGeometry){const d=points.map((p,i)=>`${i?'L':'M'} ${p[1]} ${p[0]}`).join(' ');routeSvg.innerHTML=`<path class="route-line surveyed" d="${d}"/>`;const ys=points.map(p=>p[0]),xs=points.map(p=>p[1]);fitBounds([[Math.min(...ys)-90,Math.min(...xs)-90],[Math.max(...ys)+90,Math.max(...xs)+90]])}else if(!D.routeTemplates?.[`${a.id}>${b.id}`]&&a.bldg===b.bldg&&a.floor===b.floor&&pa&&pb){routeSvg.innerHTML=`<path class="route-line orientation" d="M ${pa[1]} ${pa[0]} L ${pb[1]} ${pb[0]}"/>`;fitBounds([[Math.min(pa[0],pb[0])-120,Math.min(pa[1],pb[1])-120],[Math.max(pa[0],pb[0])+120,Math.max(pa[1],pb[1])+120]])}else if(pb)focusRoom(b)}
function currentRouteStep(){return state.route?.steps?.[state.routeIndex]||null}
function renderRoute(){const r=state.route;if(!r)return;const step=currentRouteStep(),pct=((state.routeIndex+1)/r.steps.length)*100;$('routeTitle').textContent=`${r.a.id} → ${r.b.id}`;$('routeStatus').textContent=`Step ${state.routeIndex+1} of ${r.steps.length} · ${r.precision}${r.note?' · '+r.note:''}`;$('nextInstruction').textContent=step.text;$('routeSteps').innerHTML=r.steps.map((s,i)=>`<li class="${i===state.routeIndex?'current':''}"><b>${s.icon||'•'}</b> ${s.text}</li>`).join('');$('routeProgress').style.width=pct+'%';const cp=checkpointBy(step.anchor);$('routeLandmark').hidden=!step.confirm&&!cp;if(step.confirm||cp){$('routeLandmarkIcon').textContent=step.icon||checkpointIcon(cp?.type);$('routeLandmarkName').textContent=cp?.name||'Visual landmark';$('routeLandmarkHint').textContent=step.confirm||''}renderGuideLens();renderTourGuide()}
function renderGuideLens(){if(!state.route||$('guideLens').hidden)return;const s=currentRouteStep();$('guideLensIcon').textContent=s?.icon||'↑';$('guideLensText').textContent=s?.text||'';$('guideLensMeta').textContent=`${state.heading?Math.round(state.heading)+'° heading · ':''}${state.route.precision}`}
function renderTourGuide(){if(!$('tourGuideBar'))return;if(!state.route){$('tourGuideBar').hidden=true;return}const s=currentRouteStep();$('tourGuideBar').hidden=false;$('tourGuideIcon').textContent=s?.icon||'↑';$('tourGuideText').textContent=s?.text||''}
function speak(){if(!state.route||!('speechSynthesis'in window))return;speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(currentRouteStep().text))}
function nextRouteStep(){if(!state.route)return;if(state.routeIndex<state.route.steps.length-1){state.routeIndex++;renderRoute();if(state.voice)speak()}else toast('Route complete')}
$('nextStep').onclick=nextRouteStep;$('prevStep').onclick=()=>{if(state.route&&state.routeIndex>0){state.routeIndex--;renderRoute()}};$('speakStep').onclick=speak;$('endRoute').onclick=()=>{state.route=null;routeSvg.innerHTML='';$('routeCard').hidden=true;$('guideLens').hidden=true;renderTourGuide()};$('visualCheck').onclick=openTour;$('recalibrate').onclick=openPosition;$('guideLensClose').onclick=()=>$('guideLens').hidden=true;$('tourBackToGuide').onclick=()=>{closeTour();$('routeCard').hidden=false};
$('confirmLandmark').onclick=()=>{const s=currentRouteStep();if(!s)return;const cp=checkpointBy(s.anchor);if(cp)anchorAt(cp);nextRouteStep()};
$('lostBtn').onclick=openLostRecovery;
function openLostRecovery(){if(!state.route){openPosition();return}const step=currentRouteStep();$('lostContext').innerHTML=`<b>Current instruction</b><p>${step.text}</p><small>Choose something you can definitely see. This re-orients the guide instead of guessing your position.</small>`;const anchors=state.route.steps.map((s,i)=>({s,i,c:checkpointBy(s.anchor)})).filter(x=>x.c||x.s.confirm);$('lostChoices').innerHTML=anchors.map(x=>`<button class="result" data-route-index="${x.i}"><span class="result-icon">${x.s.icon||'◉'}</span><span class="result-copy"><b>${x.c?.name||'Route landmark'}</b><small>${x.s.confirm||x.s.text}</small></span><em>${x.c?.pos?'Anchor':'Guide'}</em></button>`).join('')||'<p class="empty">No surveyed landmarks on this route yet. Use the 360° visual check or reset your position.</p>';$('lostChoices').querySelectorAll('[data-route-index]').forEach(b=>b.onclick=()=>{const i=+b.dataset.routeIndex,s=state.route.steps[i],c=checkpointBy(s.anchor);state.routeIndex=i;if(c)anchorAt(c);renderRoute();closeSheets();toast('Route re-oriented')});openSheet('lostSheet')}
$('lostTour').onclick=openTour;$('lostPosition').onclick=openPosition;

/* ---------- immersive tour ---------- */
function openTour(){closeSheets();$('tourSheet').hidden=false;if(!state.tourLoaded){$('tourFrame').src=D.tourUrl;state.tourLoaded=true}renderTourGuide();document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode==='tour'))}
function closeTour(){$('tourSheet').hidden=true;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode==='map'))}
$('closeTour').onclick=closeTour;$('openTourExternal').onclick=()=>window.open(D.tourUrl,'_blank','noopener');function setMode(mode){document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='tour'){openTour();return}if(mode==='guide'){showAssistant();return}if(mode==='map')$('tourSheet').hidden=true}document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));

/* ---------- concierge / intent recognition ---------- */
function addFeed(s,who){const d=document.createElement('div');d.className=who;d.textContent=s;$('assistantFeed').appendChild(d);$('assistantFeed').scrollTop=$('assistantFeed').scrollHeight}
function showAssistant(prefill=''){$('assistantCard').hidden=false;renderSuggestions();if(prefill){$('assistantInput').value=prefill;setTimeout(()=>$('assistantSend').click(),30)}else $('assistantInput').focus()}
function renderSuggestions(){const box=$('assistantSuggestions');box.innerHTML=[...D.intentGroups.slice(0,6),{id:'lost',label:'I’m lost'}].map(i=>`<button data-intent="${i.id}">${i.label}</button>`).join('');box.querySelectorAll('[data-intent]').forEach(b=>b.onclick=()=>{if(b.dataset.intent==='lost'){addFeed('I’m lost','me');addFeed('No problem. I’ll re-orient you from a landmark instead of guessing your position.','bot');openLostRecovery();return}const it=D.intentGroups.find(i=>i.id===b.dataset.intent);if(it)resolveIntent(it)})}
function bestPlace(text){const q=norm(text);let best=null,score=0;for(const p of D.places){const hay=[p.name,p.kind,p.description,...(p.keywords||[])].map(norm);let s=0;for(const h of hay){if(q===h)s=Math.max(s,100);else if(q.includes(h)||h.includes(q))s=Math.max(s,70);for(const w of q.split(' '))if(w.length>2&&h.includes(w))s+=7}if(s>score){score=s;best=p}}return score>=12?best:null}
function bestIntent(text){const q=norm(text);let best=null,score=0;for(const it of D.intentGroups){let s=0;for(const k of it.keywords||[]){const h=norm(k);if(q===h)s+=100;else if(q.includes(h)||h.includes(q))s+=50;for(const w of q.split(' '))if(w.length>2&&h.includes(w))s+=5}if(s>score){score=s;best=it}}return score>=10?best:null}
function resolveIntent(it){const p=placeBy(it.place);if(!p)return;const r=p.room?roomBy(p.room):null;addFeed(`${p.name}: ${p.description}${r?` I can guide you to ${r.id}.`:' I can show you the current campus space in the 360° tour while its exact indoor anchor is being surveyed.'}`,'bot');selectEntity({type:'place',value:p})}
function nearestFacility(type){if(!state.position?.pos)return null;return allCheckpoints().filter(c=>c.type===type&&c.pos).map(c=>({c,d:Math.hypot(c.pos[0]-state.position.pos[0],c.pos[1]-state.position.pos[1])})).sort((a,b)=>a.d-b.d)[0]?.c||null}
function assistant(msg){
 const text=(msg||'').trim();if(!text)return;addFeed(text,'me');const low=text.toLowerCase();
 if(/i(?:'m| am) lost|\blost\b|where am i/.test(low)){addFeed(state.lastConfirmed?`Your last confirmed anchor was ${state.lastConfirmed.name}. I’ll help you re-orient from something you can see.`:'I won’t guess your location. Pick a landmark you can see or use the 360° view.','bot');openLostRecovery();return}
 if(/step[- ]?free|wheelchair|accessible/.test(low)){state.stepFree=true;store.set('cn_stepfree',true);$('stepFreeToggle').checked=true;addFeed('Step-free preference is on. I will only call a route step-free when a surveyed link confirms it.','bot')}
 const seenText=low.replace(/^(i can see|i see|i am by|i'm by|near)\s+/,'');
 const seen=checkpointMatches(seenText)[0];
 if(seen&&/i can see|i see|i am by|i'm by|near/.test(low)){anchorAt(seen.c);addFeed(`Great — I’ve anchored you to ${seen.c.name}${seen.c.pos?' precisely on the map':''}.`,'bot');return}
 const facilityType=/toilet|loo|bathroom|wc/.test(low)?'toilet':/printer|print|refill/.test(low)?'printer':/water|fountain|bottle/.test(low)?'water':/lift|elevator/.test(low)?'lift':null;
 if(facilityType&&/nearest|closest|where/.test(low)){const c=nearestFacility(facilityType);if(c){addFeed(`The nearest surveyed ${facilityType} anchor is ${c.name}. I can use it as a precise landmark.`,'bot');anchorAt(c)}else addFeed(`I know you need a ${facilityType}, but no precise ${facilityType} anchor has been surveyed near your current position yet. Open the 360° tour or use local signage rather than me inventing a location.`,'bot');return}
 let m=low.match(/(?:i(?:'m| am) at|i am in|start(?:ing)? at|from)\s+([a-z]\d{3}[a-z]?)/i);if(m){const r=roomBy(m[1]);if(r){state.start=r;const p=posFor(r);if(p){const cp=allCheckpoints().find(c=>c.room===r.id&&c.pos);setPosition(p,'verified room',r.id,cp?.id||null,100)}addFeed(`Got it — ${r.id} in ${r.bldg}, ${floorLabel(r.floor)} is your start.${p?' Your position is anchored to its verified pin.':' Its exact doorway still needs survey verification.'}`,'bot');return}}
 const code=(text.match(/\b[A-Z]\d{3}[A-Z]?\b/i)||[])[0];if(code){const r=roomBy(code);if(r){const wantsRoute=/take|go|directions|route|guide|to\b/.test(low);addFeed(`${r.id} is in ${r.bldg}, ${floorLabel(r.floor)}. ${verified(r)?'Its doorway pin is verified.':'I know the correct floor section, but I will not fake an exact doorway.'}`,'bot');if(wantsRoute)routeTo(r);else selectEntity({type:'room',value:r});return}}
 const it=bestIntent(text);if(it){resolveIntent(it);return}const p=bestPlace(text);if(p){const r=p.room?roomBy(p.room):null;addFeed(`${p.name}: ${p.description}${r?` It is linked to ${r.id}.`:' Use Explore for a real visual look while its exact indoor anchor is being surveyed.'}`,'bot');if(/take|go|directions|route|guide/.test(low)&&r)routeTo(r);else selectEntity({type:'place',value:p});return}
 addFeed('I can understand rooms, exams, IT help, study space, food, student support, sport, arts, accessibility, “I’m lost”, and visible landmarks such as “I can see the lockers”.','bot')
}
$('assistantClose').onclick=()=>$('assistantCard').hidden=true;$('assistantSend').onclick=()=>{const v=$('assistantInput').value;$('assistantInput').value='';assistant(v)};$('assistantInput').onkeydown=e=>{if(e.key==='Enter')$('assistantSend').click()};

/* ---------- home / saved / settings ---------- */
function renderHome(){const icons={'it-help':'⌘','exam-help':'✓','study':'▤','food':'☕','support':'♥','sport':'◉','arts':'◇','toilet':'WC','access':'↕','careers':'↗'};$('intentGrid').innerHTML=D.intentGroups.slice(0,8).map(i=>`<button class="intent" data-home-intent="${i.id}"><i>${icons[i.id]||'✦'}</i>${i.label}</button>`).join('');$('intentGrid').querySelectorAll('[data-home-intent]').forEach(b=>b.onclick=()=>{const it=D.intentGroups.find(i=>i.id===b.dataset.homeIntent);if(it)resolveIntent(it)})}
$('askAnything').onclick=()=>showAssistant();$('welcomeClose').onclick=()=>$('welcomeCard').hidden=true;
function renderSaved(){const arr=[...state.saved];$('savedResults').innerHTML=arr.map(key=>{const [kind,id]=key.split(':');const sel=kind==='room'?{type:'room',value:roomBy(id)}:{type:'place',value:placeBy(id)};return sel.value?resultMarkup(sel):''}).join('')||'<p class="empty">Nothing saved yet.</p>';bindResults($('savedResults'))}
$('menuBtn').onclick=()=>{openSheet('settingsSheet');$('stepFreeToggle').checked=state.stepFree;$('voiceToggle').checked=state.voice;$('profileSelect').value=state.profile};$('positionBtn').onclick=openPosition;$('openTourSettings').onclick=openTour;$('stepFreeToggle').onchange=e=>{state.stepFree=e.target.checked;store.set('cn_stepfree',state.stepFree)};$('voiceToggle').onchange=e=>{state.voice=e.target.checked;store.set('cn_voice',state.voice)};$('profileSelect').onchange=e=>{state.profile=e.target.value;store.set('cn_profile',state.profile);toast(`Route profile: ${state.profile}`)};

/* ---------- precision map studio ---------- */
$('studioBtn').onclick=()=>{renderStudio();openSheet('studioSheet')};
function studioTab(name){document.querySelectorAll('[data-studio-tab]').forEach(b=>b.classList.toggle('active',b.dataset.studioTab===name));['rooms','anchors','links'].forEach(n=>$(`studio${n[0].toUpperCase()+n.slice(1)}Panel`).hidden=n!==name)}
document.querySelectorAll('[data-studio-tab]').forEach(b=>b.onclick=()=>studioTab(b.dataset.studioTab));
function renderStudio(){
 const sorted=[...D.rooms].sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true}));$('studioRoom').innerHTML=sorted.map(r=>`<option value="${r.id}">${r.id} — ${r.bldg} ${floorLabel(r.floor)}${verified(r)?' ✓':''}</option>`).join('');
 $('anchorType').innerHTML=(D.surveyTypes||[]).map(t=>`<option value="${t.id}">${t.icon} ${t.label}</option>`).join('');
 const buildings=[...new Set(D.rooms.map(r=>r.bldg))];$('anchorBuilding').innerHTML=buildings.map(b=>`<option>${b}</option>`).join('');
 const cps=allCheckpoints();const opts=cps.filter(c=>c.pos).map(c=>`<option value="${c.id}">${c.name}${c.seed?' · built-in':''}</option>`).join('');$('edgeFrom').innerHTML=opts;$('edgeTo').innerHTML=opts;
 $('anchorList').innerHTML=(state.survey.checkpoints||[]).map(c=>`<div class="result"><span class="result-icon">${checkpointIcon(c.type)}</span><span class="result-copy"><b>${c.name}</b><small>${c.bldg} · ${floorLabel(c.floor)} · ${c.id}</small></span><button class="tiny-btn" data-copy-cp="${c.id}">QR link</button><button class="tiny-btn danger" data-del-cp="${c.id}">×</button></div>`).join('')||'<p class="empty">No custom survey anchors yet.</p>';
 $('edgeList').innerHTML=(state.survey.edges||[]).map((e,i)=>`<div class="result"><span class="result-icon">↔</span><span class="result-copy"><b>${checkpointBy(e.from)?.name||e.from} → ${checkpointBy(e.to)?.name||e.to}</b><small>${e.instruction||'Connected'} · ${e.access}${e.stepFree?' · step-free':''}</small></span><button class="tiny-btn danger" data-del-edge="${i}">×</button></div>`).join('')||'<p class="empty">No surveyed anchor links yet.</p>';
 $('anchorList').querySelectorAll('[data-del-cp]').forEach(b=>b.onclick=()=>{const id=b.dataset.delCp;state.survey.checkpoints=state.survey.checkpoints.filter(c=>c.id!==id);state.survey.edges=state.survey.edges.filter(e=>e.from!==id&&e.to!==id);saveSurvey();renderCheckpoints();renderStudio()});
 $('anchorList').querySelectorAll('[data-copy-cp]').forEach(b=>b.onclick=async()=>{const u=new URL(location.href);u.search='';u.searchParams.set('cp',b.dataset.copyCp);try{await navigator.clipboard.writeText(u.toString());toast('Checkpoint link copied')}catch{prompt('Copy this checkpoint URL',u.toString())}});
 $('edgeList').querySelectorAll('[data-del-edge]').forEach(b=>b.onclick=()=>{state.survey.edges.splice(+b.dataset.delEdge,1);saveSurvey();renderStudio()});updateAccuracy()
}
$('studioPlace').onclick=()=>calibrationMode(roomBy($('studioRoom').value));
$('anchorPlace').onclick=()=>{const name=$('anchorName').value.trim();if(!name){toast('Give the anchor a name');return}const id='SURVEY_'+Date.now().toString(36).toUpperCase();state.placingAnchor={id,name,type:$('anchorType').value,bldg:$('anchorBuilding').value,floor:$('anchorFloor').value,keywords:[name.toLowerCase()]};closeSheets();mapEl.classList.add('calibrating');toast(`Tap the exact position for ${name}`)};
$('edgeAdd').onclick=()=>{const from=$('edgeFrom').value,to=$('edgeTo').value;if(!from||!to||from===to){toast('Choose two different anchors');return}state.survey.edges.push({from,to,instruction:$('edgeInstruction').value.trim()||`Continue to ${checkpointBy(to)?.name||to}.`,stepFree:$('edgeStepFree').checked,access:$('edgeAccess').value,createdAt:new Date().toISOString()});saveSurvey();renderStudio();toast('Survey link added')};
$('exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:6,created:new Date().toISOString(),roomCalibration:state.cal,survey:state.survey},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='campus-navigator-v6-survey.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$('importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const j=JSON.parse(rd.result);state.cal=j.roomCalibration||j.calibration||state.cal;state.survey=j.survey||state.survey;store.set('cn_calibration',state.cal);saveSurvey();renderRooms();renderCheckpoints();renderStudio();toast('Survey imported')}catch{toast('Invalid survey file')}};rd.readAsText(f)};
$('clearCalibration').onclick=()=>{if(confirm('Clear all local room corrections, anchors and links?')){state.cal={};state.survey=structuredClone(EMPTY_SURVEY);store.set('cn_calibration',{});saveSurvey();renderRooms();renderCheckpoints();renderStudio()}};

document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=b.dataset.tab;if(t==='home'){$('welcomeCard').hidden=false;fitAll()}if(t==='find')$('searchBtn').click();if(t==='tour')openTour();if(t==='saved'){renderSaved();openSheet('savedSheet')}});

/* ---------- startup / deep links ---------- */
window.addEventListener('online',()=>$('offline').hidden=true);window.addEventListener('offline',()=>$('offline').hidden=false);$('offline').hidden=navigator.onLine;
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderHome();renderRooms();renderCheckpoints();renderPosition();renderStudio();renderSuggestions();$('stepFreeToggle').checked=state.stepFree;$('voiceToggle').checked=state.voice;$('profileSelect').value=state.profile;
const url=new URL(location.href),action=url.searchParams.get('action'),cpId=url.searchParams.get('cp');
setTimeout(()=>{if(img.complete)fitAll();if(cpId){const c=checkpointBy(cpId);if(c){anchorAt(c);showAssistant(`I am by ${c.name}`)}}if(action==='search')$('searchBtn').click();if(action==='assistant')showAssistant();if(action==='tour')openTour()},80);
})();
